// The CLI "other device" fixture of the M1-S5 contract suite (docs/test-plans/M1-S5.md §Fixtures; ADR-0007
// `e2eeAccount`). It stands in for the user's desktop or phone: a fresh profile that joins the test's sync account,
// turns E2EE on, creates a folder and notes, and syncs. As found in spike S3, `e2ee enable` persists the master key
// only when it runs inside `joplin batch` together with `sync` (CLI 3.7.1), so everything runs in one batch.
// Input (stdin, one JSON object; never argv, so the passwords stay out of /proc/*/cmdline):
//   {"syncUrl","email","password","masterPassword","folder","notes":[{"title","body"}]}
// Output: the CLI's output, then one last line `RESULT {"e2ee": "...", "notes": [{"id","title"}]}`.
// Titles, bodies and the folder name are generated by the test: no quotes, backslashes or newlines.
import { spawn } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';

const readStdin = async () => {
	const chunks = [];
	for await (const chunk of process.stdin) chunks.push(chunk);
	return JSON.parse(Buffer.concat(chunks).toString('utf8'));
};

const joplin = (profile, args, input) => new Promise((resolve, reject) => {
	const child = spawn('joplin', ['--profile', profile, ...args], { stdio: ['pipe', 'pipe', 'pipe'] });
	let output = '';
	child.stdout.on('data', chunk => {
		output += chunk;
		process.stdout.write(chunk);
	});
	child.stderr.on('data', chunk => {
		output += chunk;
		process.stderr.write(chunk);
	});
	child.on('error', reject);
	child.on('close', code => (code === 0 ? resolve(output) : reject(new Error(`joplin ${args[0]} exited ${code}`))));
	child.stdin.end(input ?? '');
});

const plan = await readStdin();
for (const value of [plan.folder, ...plan.notes.flatMap(n => [n.title, n.body])]) {
	if (/["\\\n\r]/.test(value)) throw new Error(`unsafe batch value: ${JSON.stringify(value)}`);
}
const profile = '/tmp/home/device-profile';
mkdirSync(profile, { recursive: true, mode: 0o700 });

await joplin(profile, ['config', '--import'], JSON.stringify({
	'sync.target': 9,
	'sync.9.path': plan.syncUrl,
	'sync.9.username': plan.email,
	'sync.9.password': plan.password,
}));

const batch = [
	`e2ee enable --password "${plan.masterPassword}"`,
	`mkbook "${plan.folder}"`,
	`use "${plan.folder}"`,
	...plan.notes.flatMap(n => [`mknote "${n.title}"`, `set "${n.title}" body "${n.body}"`]),
	'sync',
	'ls --format json',
].join('\n');
const batchFile = '/tmp/home/device-batch.txt';
writeFileSync(batchFile, `${batch}\n`, { mode: 0o600 });
const output = await joplin(profile, ['batch', batchFile]);

const listed = output.split('\n').filter(line => line.startsWith('[')).pop();
if (!listed) throw new Error('the batch printed no `ls --format json` line');
const items = JSON.parse(listed);
const notes = plan.notes.map(n => {
	const item = items.find(i => i.title === n.title);
	if (!item) throw new Error(`note ${JSON.stringify(n.title)} not listed after the batch`);
	return { id: item.id, title: n.title };
});

const status = await joplin(profile, ['e2ee', 'status']);
const e2ee = /Encryption is:\s*(\w+)/.exec(status)?.[1] ?? 'unknown';
process.stdout.write(`\nRESULT ${JSON.stringify({ e2ee, notes })}\n`);
